VAGRANTFILE_API_VERSION = '2'
name = '{appName}'
box = 'trusty64'
box_url = 'https://cloud-images.ubuntu.com/vagrant/trusty/current/trusty-server-cloudimg-amd64-vagrant-disk1.box'
ip = '192.168.111.111'

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

    config.berkshelf.berksfile_path = './Berksfile'
    config.omnibus.chef_version = :latest
    config.vm.box = box
    config.vm.box_url = box_url
    config.vm.hostname = "local.#{name}"
    config.vm.network :private_network, ip: ip

    config.vm.provider :virtualbox do |vb|
        vb.name = name
    end

    config.vm.synced_folder(
        '.',
        "/home/vagrant/#{name}",
        owner: 'vagrant',
        mount_options: ['dmode=775']
    )

    config.vm.provision :chef_solo do |chef|
        chef.run_list = %w(
            nodejs
            mongodb
        )
    end
end
