name = '{invent}'
ip = '192.168.123.125'
box = 'saucy64'
box_url = 'http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_ubuntu-13.10_chef-provisionerless.box'

hostname = "local.#{name}"

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

    config.vm.box = box
    config.vm.box_url = box_url

    config.vm.provider :virtualbox do |vb|
        vb.name = name
    end

    config.vm.network :private_network, ip: ip

    config.vm.hostname = hostname

    config.vm.synced_folder(
        '.',
        "/home/vagrant/#{name}",
        :owner => 'vagrant',
        :mount_options => ['dmode=775']
    )

    config.vm.provision :chef_solo do |chef|
        chef.cookbooks_path = 'cookbooks'
        chef.json = {
            :project => {
                :name => name
            },
            :run_list => %w{
                nodejs
                mongodb
            },
            :nodejs => {
                :install_method => 'package',
                :version => '0.10.28',
                :npm => '1.4.13'
            }
        }
    end
end
