name = '{appName}'

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

    config.vm.box = 'trusty64'
    config.vm.box_url = 'https://cloud-images.ubuntu.com/vagrant/trusty/current/trusty-server-cloudimg-amd64-vagrant-disk1.box'
    config.berkshelf.berksfile_path = './Berksfile'
    config.omnibus.chef_version = :latest
    config.vm.network :private_network, ip: '192.168.111.111'
    config.vm.hostname = "local.#{name}"


    config.vm.provider :virtualbox do |vb|
        vb.name = name
    end    

    config.vm.synced_folder(
        '.',
        "/home/vagrant/#{name}",
        :owner => 'vagrant',
        :mount_options => ['dmode=775']
    )

    config.vm.provision :chef_solo do |chef|
        chef.cookbooks_path = 'cookbooks'
        chef.json = {
            :project => {
                :name => name
            },
            :run_list => %w{
                nodejs
                mongodb
            },
            :nodejs => {
                :install_method => 'package',
                :version => '0.10.31',
                :npm => '1.4.23'
            }
        }
    end
end
